apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
secrets:
- name: kube-gateway-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-reader
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-reader
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: cluster-reader
subjects:
- kind: ServiceAccount
  name: sa
---
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  tls:
    - hosts:
      - kube-gateway.apps.example.com
      secretName: kube-gateway-jwt-secret
  rules:
  - host: kube-gateway.apps.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc
            port:
              number: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: 1
  template:
    spec:
      initContainers:
      - image: web-app
        name: kube-gateway-web-app
        volumeMounts:
        - name: web-app
          mountPath: "/app/web"
        command:
        - "/bin/cp"
        - "-r"
        - "/data/web/public"
        - "/app/web/"
      containers:
      - image: proxy
        name: kube-gateway
        ports:
        - name: https
          containerPort: 8080
        volumeMounts:
        - name: secrets
          mountPath: "/secrets"
        - name: web-app
          mountPath: "/app/web"
        env:
        - name: API_URL
          value: "https://kubernetes.default.svc"
        - name: ROUTE_URL
          value: "http://kube-gateway.apps.example.com"
        - name: TOKEN_PASSTHROUGH
          value: "false"
        - name: LISTEN
          value: "http://0.0.0.0:8080"
        command:
        - "./kube-gateway"
        - "-api-server=$(API_URL)"
        - "-ca-file=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
        - "-oauth-server-disable"
        - "-base-address=https://$(ROUTE_URL)"
        - "-listen=$(LISTEN)"
        - "-jwt-token-key-file=/secrets/cert.pem"
        - "-k8s-bearer-token-file=/var/run/secrets/kubernetes.io/serviceaccount/token"
        - "-k8s-bearer-token-passthrough=$(TOKEN_PASSTHROUGH)"
      volumes:
      - name: secrets
        secret:
          secretName: kube-gateway-jwt-secret
      - name: web-app
        emptyDir: {}
      serviceAccountName: sa