---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: kube-gateway-secrets
  labels:
    app: kube-gateway
  name: kube-gateway-svc
  namespace: kube-gateway
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kube-gateway
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-gateway
  name: kube-gateway
  namespace: kube-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-gateway
  template:
    metadata:
      labels:
        app: kube-gateway
    spec:
      containers:
      - command:
        - ./kube-gateway
        - -api-server=$(API_URL)
        - -gateway-listen=$(LISTEN)
        - -api-server-ca-file=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - -api-server-bearer-token-file=/var/run/secrets/kubernetes.io/serviceaccount/token
        - -gateway-key-file=/var/run/secrets/serving-cert/tls.key
        - -gateway-cert-file=/var/run/secrets/serving-cert/tls.crt
        - -jwt-public-key-name=kube-gateway-jwt
        - -jwt-request-enable=true
        - -jwt-private-key-name=kube-gateway-jwt-private
        env:
        - name: API_URL
          value: https://kubernetes.default.svc
        - name: LISTEN
          value: https://0.0.0.0:8080
        image: quay.io/kubevirt-ui/kube-gateway
        name: kube-gateway
        ports:
        - containerPort: 8080
          name: https
        volumeMounts:
        - mountPath: /var/run/secrets/serving-cert
          name: serving-cert
      serviceAccountName: kube-gateway-sa
      volumes:
      - name: serving-cert
        secret:
          secretName: kube-gateway-secrets