apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kube-gateway
  name: kube-gateway-sa
  namespace: kube-gateway
secrets:
- name: kube-gateway-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: kube-gateway
  name: kube-gateway-cluster-reader
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: kube-gateway
  name: kube-gateway-cluster-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-gateway-cluster-reader
subjects:
- kind: ServiceAccount
  name: kube-gateway-sa
  namespace: kube-gateway
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-gateway
  name: kube-gateway-svc
  namespace: kube-gateway
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kube-gateway
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-gateway
  name: kube-gateway-proxy
  namespace: kube-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-gateway
  template:
    metadata:
      labels:
        app: kube-gateway
    spec:
      containers:
      - command:
        - ./kube-gateway
        - -api-server=$(API_URL)
        - -ca-file=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - -oauth-server-disable
        - -base-address=https://$(ROUTE_URL)
        - -listen=$(LISTEN)
        - -jwt-token-key-file=/secrets/cert.pem
        - -k8s-bearer-token-file=/var/run/secrets/kubernetes.io/serviceaccount/token
        - -k8s-bearer-token-passthrough=$(TOKEN_PASSTHROUGH)
        env:
        - name: API_URL
          value: https://kubernetes.default.svc
        - name: ROUTE_URL
          value: http://kube-gateway.apps.example.com
        - name: TOKEN_PASSTHROUGH
          value: "false"
        - name: LISTEN
          value: http://0.0.0.0:8080
        image: quay.io/yaacov/kube-gateway
        name: kube-gateway
        ports:
        - containerPort: 8080
          name: https
        volumeMounts:
        - mountPath: /secrets
          name: secrets
        - mountPath: /app/web
          name: web-app
      initContainers:
      - command:
        - /bin/cp
        - -r
        - /data/web/public
        - /app/web/
        image: quay.io/yaacov/kube-gateway-web-app-novnc
        name: kube-gateway-web-app
        volumeMounts:
        - mountPath: /app/web
          name: web-app
      serviceAccountName: kube-gateway-sa
      volumes:
      - name: secrets
        secret:
          secretName: kube-gateway-jwt-secret
      - emptyDir: {}
        name: web-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: kube-gateway
  name: kube-gateway-ingress
  namespace: kube-gateway
spec:
  rules:
  - host: kube-gateway.apps.example.com
    http:
      paths:
      - backend:
          service:
            name: kube-gateway-svc
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - kube-gateway.apps.example.com
    secretName: kube-gateway-jwt-secret
