---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-gateway
  name: kube-gateway-svc
  namespace: kube-gateway
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kube-gateway
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-gateway
  name: kube-gateway
  namespace: kube-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-gateway
  template:
    metadata:
      labels:
        app: kube-gateway
    spec:
      containers:
      - command:
        - ./kube-gateway
        - -api-server=$(API_URL)
       
        - -ca-file=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - -k8s-bearer-token-file=/var/run/secrets/kubernetes.io/serviceaccount/token

        - /var/run/secrets/serving-cert/tls.key
        - /var/run/secrets/serving-cert/tls.crt

        - -base-address=https://$(ROUTE_URL)
        - -listen=$(LISTEN)

        - -jwt-token-key-file=/secrets/cert.pem
        env:
        - name: API_URL
          value: https://kubernetes.default.svc
        - name: ROUTE_URL
          value: http://kube-gateway.apps.example.com
        - name: TOKEN_PASSTHROUGH
          value: "false"
        - name: LISTEN
          value: http://0.0.0.0:8080
        image: quay.io/kubevirt-ui/kube-gateway
        name: kube-gateway
        ports:
        - containerPort: 8080
          name: https
        volumeMounts:
        - mountPath: /secrets
          name: secrets
        - mountPath: /app/web
          name: web-app
      serviceAccountName: kube-gateway-sa
      volumes:
      - name: secrets
        secret:
          secretName: kube-gateway-jwt-secret
      - emptyDir: {}
        name: web-app