apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: oc-gate-proxy
  name: oc-gate
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: oc-gate-proxy
  name: oc-gate
  namespace: oc-gate
secrets:
- name: oc-gate-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: oc-gate-proxy
  name: oc-gate-cluster-reader
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: oc-gate-proxy
  name: oc-gate-cluster-reader
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: oc-gate-cluster-reader
subjects:
- kind: ServiceAccount
  name: oc-gate
  namespace: oc-gate
---
apiVersion: v1
kind: Service
metadata:
  name: oc-gate
  namespace: oc-gate
  labels:
    app: oc-gate-proxy
spec:
  type: LoadBalancer
  selector:
    app: oc-gate-proxy
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oc-gate-ingress
  namespace: oc-gate
  labels:
    app: oc-gate-proxy
spec:
  tls:
    - hosts:
      - oc-gate.apps.example.com
      secretName: oc-gate-jwt-secret
  rules:
  - host: oc-gate.apps.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: oc-gate
            port:
              number: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oc-gate
  namespace: oc-gate
  labels:
    app: oc-gate-proxy
spec:
  selector:
    matchLabels:
      app: oc-gate-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: oc-gate-proxy
    spec:
      initContainers:
      - image: "quay.io/yaacov/oc-gate-web-app:latest"
        name: oc-gate-web-app
        volumeMounts:
        - name: web-app
          mountPath: "/app/web"
        command:
        - "/bin/cp"
        - "-r"
        - "/data/web/public"
        - "/app/web/"
      containers:
      - image: "quay.io/yaacov/oc-gate:latest"
        name: oc-gate
        ports:
        - name: oc-gate-https
          containerPort: 8080
        volumeMounts:
        - name: secrets
          mountPath: "/secrets"
        - name: web-app
          mountPath: "/app/web"
        env:
        - name: API_URL
          value: "https://kubernetes.default.svc"
        - name: ROUTE_URL
          value: "http://oc-gate.apps.example.com"
        - name: TOKEN_PASSTHROUGH
          value: "false"
        - name: LISTEN
          value: "http://0.0.0.0:8080"
        command:
        - "./oc-gate"
        - "-api-server=$(API_URL)"
        - "-skip-verify-tls"
        - "-oauth-server-disable"
        - "-base-address=https://$(ROUTE_URL)"
        - "-listen=$(LISTEN)"
        - "-jwt-token-key-file=/secrets/cert.pem"
        - "-k8s-bearer-token-file=/secrets/token"
        - "-k8s-bearer-token-passthrough=$(TOKEN_PASSTHROUGH)"
      volumes:
      - name: secrets
        secret:
          secretName: oc-gate-jwt-secret
      - name: web-app
        emptyDir: {}
      serviceAccount: oc-gate