resources:
- proxy.yaml

generatorOptions:
  disableNameSuffixHash: true

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: proxy
  newName: quay.io/yaacov/oc-gate
- name: web-app
  newName: quay.io/yaacov/oc-gate-web-app-novnc
